const app=document.getElementById('app');let answers={},index=-1;const regions=['서울','부산','대구','인천','광주','대전','울산','세종','경기','강원','충북','충남','전북','전남','경북','경남','제주'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function home(){index=-1;document.body.classList.remove('in-flow');app.innerHTML=`
<section class="hero"><div class="hero-copy"><div class="eyebrow">SUN PARTNERS · PARTNER RECRUITING</div><h1 class="partner-headline"><span class="headline-row"><span class="headline-support">이어가는</span> <span class="headline-key">보험 영업.</span></span><span class="headline-row pink"><span class="headline-key">환수 없는</span> <span class="headline-support">파트너 활동.</span></span><span class="headline-row headline-last">더 넓어진 <span class="headline-contact">고객 접점.</span></span></h1><p>여행·건강·생활·자동차까지.<br>썬파트너스와 고객에게 필요한 이야기를 시작하세요.</p><button class="cta" data-start><span>파트너 활동 상담하기</span><span class="cta-arrow" aria-hidden="true">↗</span></button><div class="secondary">보험설계사 · 조직 관리자 · 겸업 파트너 모집</div><p class="hero-terms">환수 미적용 대상 상품과 활동 조건은 상담 시 확인해 주세요.<br>기존 보험계약의 수수료·환수 규정과는 별개입니다.</p></div><div class="portrait"><img src="model.png" alt="밝게 웃는 썬파트너스 여성 브랜드 캐릭터"><div class="portrait-label"><small>YOUR NEXT CHAPTER</small>지금의 당신에게,<br>가능성을 하나 더.</div></div></section>
<div class="service-strip" aria-label="서비스 분야"><span>크루즈 여행</span><span>헬스케어</span><span>생활가전·라이프케어</span><span>자동차 리스·렌탈</span><span>줄기세포 서비스</span></div>
<section class="section story-empathy" id="opportunity"><div class="eyebrow">01 / YOUR EVERYDAY STORY</div><h2>“오늘은 누구에게<br><span class="topic-accent">연락하지?</span>”</h2><figure class="story-photo "><img src="assets/story-empathy.png" alt="사무실에서 휴대전화를 바라보며 고객에게 연락을 고민하는 한국인 여성 설계사" width="1536" height="1024" loading="lazy"><figcaption>스토리 이해를 돕기 위한 AI 연출 이미지입니다.</figcaption></figure><div class="story-split"><p class="story-lead">연락처는 쌓였지만,<br>선뜻 전화를 걸기는 어렵습니다.</p><div><p>또 보험 이야기로 들릴까 봐.<br>오랜만의 안부가 권유처럼 느껴질까 봐.<br>연락할 이유를 찾다가, 하루가 지나갑니다.</p><p class="story-question">고객에게 필요한 이야기로<br>다시 시작할 수 있다면 어떨까요?</p></div></div></section>
<section class="story-daily"><div class="section"><div class="eyebrow">A DIFFERENT START</div><h2>고객의 일상에는<br>보험 말고도 <span class="topic-accent">필요한 것</span>이 있습니다.</h2><figure class="story-photo story-photo-travel"><img src="assets/story-travel.png" alt="크루즈 갑판에서 여행을 즐기는 한국인 부모님과 성인 딸" width="1536" height="1024" loading="lazy"><figcaption>스토리 이해를 돕기 위한 AI 연출 이미지입니다.</figcaption></figure><div class="daily-grid"><article><span>가족과의 시간</span><h3>“부모님과 <span class="topic-accent">여행</span>을<br>한번 떠나고 싶어요.”</h3><p>함께할 여행을 계획하는 순간.</p></article><article><span>새로운 이동</span><h3>“<span class="topic-accent">차를 바꿀 때</span>가 됐는데,<br>어떤 방식이 좋을까요?”</h3><p>나에게 맞는 차량 이용을 고민하는 순간.</p></article><article><span>일상의 변화</span><h3>“가족의 <span class="topic-accent">건강</span>도,<br>집안 <span class="topic-accent">살림</span>도 챙겨야죠.”</h3><p>건강관리와 생활에 필요한 것을 찾는 순간.</p></article></div><p class="story-bridge">대화의 시작은 <strong>고객의 일상</strong>에 있습니다.</p><small class="story-caption">서비스 이해를 돕기 위한 가상의 대화 예시입니다.</small></div></section>
<section class="collection" id="services"><div class="section"><div class="section-heading"><div><div class="eyebrow">02 / LIFE & OPPORTUNITY</div><h2>고객의 일상에 닿는<br><span class="topic-accent">다섯 가지 서비스.</span></h2></div><p>필요가 다른 만큼, 대화의 시작도 다양하게.<br>썬파트너스가 함께 안내하는 서비스입니다.</p></div><figure class="service-visual"><img src="assets/services-ai.png" alt="크루즈, 건강관리 공간, 생활가전, 자동차와 세포를 표현한 서비스 이미지" loading="lazy"><figcaption>서비스 이해를 돕기 위한 AI 연출 이미지로 실제 상품·시설과 다를 수 있습니다.</figcaption></figure><div class="service-grid">
<article class="service-card travel"><span class="service-no">01 — TRAVEL</span><div class="service-symbol" aria-hidden="true">↗</div><h3><span class="topic-accent">크루즈</span> 여행</h3><p>가족과 함께 누리고 싶은 여행.<br>크루즈 라이프서비스와 연계 혜택을 알아보는 새로운 대화를 시작합니다.</p><span class="card-note">여행 계획 · 라이프서비스</span></article>
<article class="service-card"><span class="service-no">02 — HEALTH</span><div class="service-symbol" aria-hidden="true">＋</div><h3><span class="topic-accent">헬스케어</span></h3><p>나와 가족의 건강을 돌아보는 계기.<br>건강 스크리닝과 건강관리 서비스의 구성 및 이용 조건을 안내합니다.</p><span class="card-note">건강 스크리닝 · 건강관리</span></article>
<article class="service-card"><span class="service-no">03 — DAILY LIFE</span><div class="service-symbol" aria-hidden="true">⌂</div><h3><span class="topic-accent">생활가전</span>·라이프케어</h3><p>생활 가까이에 있는 필요부터.<br>프리미엄 생활가전과 일상에 맞는 라이프케어 서비스를 살펴봅니다.</p><span class="card-note">생활가전 · 일상 서비스</span></article>
<article class="service-card"><span class="service-no">04 — MOBILITY</span><div class="service-symbol" aria-hidden="true">→</div><h3>자동차 <span class="topic-accent">리스·렌탈</span></h3><p>차량이 필요한 고객에게 또 하나의 선택.<br>이용 목적에 맞는 리스·렌탈 방식과 개별 계약 조건을 확인합니다.</p><span class="card-note">차량 이용 상담 · 조건 확인</span></article>
<article class="service-card"><span class="service-no">05 — CELL SERVICE</span><div class="service-symbol" aria-hidden="true">◎</div><h3><span class="topic-accent">줄기세포</span> 서비스</h3><p>줄기세포 관련 서비스가 궁금하다면.<br>실제 제공 범위와 이용 절차, 대상 및 조건을 상담에서 확인할 수 있습니다.</p><span class="card-note">서비스 범위 · 이용 절차 안내</span></article>
<article class="service-card service-invite"><span class="service-no">FIND YOUR POSSIBILITY</span><h3>어떤 활동이<br>나에게 맞을까요?</h3><p>지금의 경력과 상황부터<br>편하게 이야기해 주세요.</p><button class="text-link" data-start>활동 상담하기 ↗</button></article></div><p class="fine-print">상품별 제공 서비스·혜택·비용·이용 조건은 해당 상품의 공식 안내와 청약서·약관을 기준으로 합니다. 건강 스크리닝은 질병 확진과 구분되며, 줄기세포 서비스의 구체적인 제공 내용은 상담에서 확인해 주세요.</p></div></section>
<section class="section story-conversation"><div><div class="eyebrow">03 / START WITH A QUESTION</div><h2>상품을 먼저 권하기보다,<br><span class="topic-accent">필요한 이야기</span>를 먼저.</h2><p>새로운 상품을 소개하기 전에,<br>고객의 계획과 관심사를 물어보세요.</p><figure class="story-photo "><img src="assets/story-conversation.png" alt="밝은 상담 공간에서 편안하게 대화하는 한국인 여성 상담사와 고객" width="1536" height="1024" loading="lazy"><figcaption>스토리 이해를 돕기 위한 AI 연출 이미지입니다.</figcaption></figure></div><div class="conversation-card"><span class="conversation-label">이렇게 대화를 시작해 보세요</span><p class="chat-question">부모님과 여행을 계획하고 계세요?</p><p class="chat-answer">네, 이번에는 조금 특별하게 다녀오고 싶어요.</p><p class="chat-question">그럼 크루즈 여행은 어떠세요?<br>일정과 이용 조건부터 함께 알아볼까요?</p><div class="conversation-end">안부에서 관심으로.<br><strong>관심에서 새로운 상담으로.</strong></div><small class="story-caption">실제 고객 후기나 상담 실적이 아닌 대화 예시입니다.</small></div></section>
<section class="story-promise"><div class="section"><div class="eyebrow">WITH SUN PARTNERS</div><h2>쌓아온 관계를,<br><span class="topic-accent">더 넓은 활동</span>으로.</h2><p>기존 보험 영업은 이어가면서,<br>환수 없는 파트너 활동을 더해보세요.<br>여행·건강·생활·자동차까지, 고객과 나눌 이야기가 넓어집니다.</p><p class="fine-print">환수 미적용 대상 상품과 활동 조건은 상담 시 확인해 주세요. 기존 보험계약의 수수료·환수 규정과는 별개입니다.</p><button class="cta" data-start><span>나에게 맞는 파트너 활동 알아보기</span><span class="cta-arrow" aria-hidden="true">↗</span></button></div></section>
<section class="section audience" id="partners"><div class="eyebrow">04 / YOUR EXPERIENCE MATTERS</div><h2>경력은 이어가고,<br>활동의 폭은 넓히고.</h2><div class="audience-grid"><article><span>FOR PLANNERS</span><h3>보험설계사</h3><p>쌓아온 고객 관계를 바탕으로, 여행·건강·일상의 새로운 관심사를 함께 나눌 수 있는 활동을 알아보세요.</p></article><article><span>FOR LEADERS</span><h3>조직 관리자</h3><p>팀의 상황에 맞는 활동 방식과 서비스 안내 방법, 기존 업무와 병행할 수 있는 조건을 상담합니다.</p></article><article><span>FOR YOUR NEXT STEP</span><h3>겸업 희망자</h3><p>현재 하는 일과 가능한 시간을 바탕으로, 실제 역할과 필요한 자격부터 차근차근 확인해 보세요.</p></article></div></section>
<section class="conditions"><div class="section"><div><div class="eyebrow">CLEAR BEFORE YOU START</div><h2>기대만큼 중요한 건,<br>정확한 조건입니다.</h2></div><div><h3>활동 내용과 보상 기준부터 확인하세요.</h3><p>실제 맡게 될 역할, 필요한 자격, 보상 지급 시점과 환수 적용 여부를 상담에서 확인한 뒤 결정하세요. 기존 보험 영업의 수수료 규정과 파트너 활동 조건은 구분해서 살펴봐야 합니다.</p><span class="condition-note">특정 소득이나 영업 성과를 보장하지 않습니다.</span></div></div></section>
<section class="section"><div class="eyebrow">05 / HOW TO START</div><h2>내게 맞는지부터,<br>차근차근 알아보세요.</h2><div class="steps-grid"><article><b>01</b><h3>상담 신청</h3><p>관심 활동과 연락 가능한 시간을 남겨주세요.</p></article><article><b>02</b><h3>내용과 조건 확인</h3><p>내 상황을 바탕으로 서비스와 활동 조건을 확인합니다.</p></article><article><b>03</b><h3>충분히 알아본 뒤 결정</h3><p>설명을 듣고 궁금한 점을 확인한 뒤 참여를 판단하세요.</p></article></div></section>
<section class="section faq" id="faq"><div><div class="eyebrow">QUESTIONS & ANSWERS</div><h2>궁금한 점을<br>먼저 확인하세요.</h2></div><div class="faq-list"><details><summary>보험 일을 하면서 알아볼 수 있나요?</summary><p>기존 경력을 이어가며 새로운 파트너 활동을 알아보는 분을 위한 상담입니다. 실제 병행 가능 여부는 현재 소속 및 계약 규정, 활동 조건을 함께 확인해 주세요.</p></details><details><summary>어떤 서비스를 취급하나요?</summary><p>크루즈 여행, 헬스케어, 생활가전·라이프케어, 자동차 리스·렌탈, 줄기세포 서비스를 안내합니다. 상품별 제공 범위와 이용 조건은 서로 다릅니다.</p></details><details><summary>경력이 없어도 상담할 수 있나요?</summary><p>겸업에 관심 있는 분도 상담을 신청할 수 있습니다. 실제 수행하는 역할과 필요한 자격·교육 여부는 상담을 통해 확인해 주세요.</p></details><details><summary>수수료와 환수 조건은 어떻게 되나요?</summary><p>상품과 활동에 따른 지급 기준·시점, 취소·해약 시 처리 및 환수 적용 범위를 확인해야 합니다. 기존 보험 계약의 수수료 규정까지 동일하게 적용된다는 의미는 아닙니다.</p></details><details><summary>상담 신청은 어떻게 진행되나요?</summary><p>아래 버튼을 누르면 관심 활동과 연락처를 입력할 수 있습니다. 개인정보 수집·이용에 동의하고 최종 신청하면 담당자에게 접수됩니다.</p></details></div></section>
<section class="closing" id="consult"><div class="eyebrow">LET’S START A CONVERSATION</div><h2>지금의 고객과,<br>어떤 이야기를 시작할 수 있을까요?</h2><p>쌓아온 경력과 고객의 관심사.<br>내게 맞는 활동부터 함께 알아보세요.</p><button class="cta" data-start><span>파트너 활동 상담하기</span><span class="cta-arrow" aria-hidden="true">↗</span></button></section>`;
app.querySelectorAll('[data-start]').forEach(b=>b.onclick=openConsult);
const nav=document.querySelector('a[href="#consult"]');if(nav)nav.onclick=e=>{e.preventDefault();openConsult()};}
let submitting=false;
function openConsult(){
 let dialog=document.getElementById('consult-dialog');
 if(dialog){dialog.showModal();document.body.classList.add('modal-open');return;}
 dialog=document.createElement('dialog');dialog.id='consult-dialog';dialog.className='consult-dialog';dialog.setAttribute('aria-labelledby','consult-title');
 const select=(id,label,values,required=false)=>`<label class="consult-field">${label}<select name="${id}" ${required?'required':''}><option value="">선택</option>${values.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`;
 const consent=(id,label,detail)=>`<div class="consent-item"><label><input type="checkbox" name="${id}" ${id==='consent'?'required':''}><span>${label}</span></label><details><summary>상세보기</summary><p>${detail}</p></details></div>`;
 dialog.innerHTML=`<header class="consult-modal-head"><h2 id="consult-title">파트너 상담</h2><button type="button" class="modal-close" aria-label="상담 신청 닫기">×</button></header><form id="partner-form"><label class="consult-field">이름 (한글 2~10자)<input name="name" placeholder="홍길동" autocomplete="name" pattern="[가-힣]{2,10}" maxlength="10" required></label><label class="consult-field">연락처 (010-0000-0000)<input name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="010-1234-5678" pattern="010-[0-9]{4}-[0-9]{4}" maxlength="13" required></label>${select('region','지역 (필수)',regions,true)}${select('contactTime','상담가능시간',['오전 9시–12시','오후 12시–6시','저녁 6시–8시','시간 협의'])}${select('ageRange','연령대',['20대','30대','40대','50대','60대 이상'])}${select('role','현재 역할',['지점장 이상','팀장 (지점장 미만)','설계사 (관리직 제외)','회사원 · 공무원','자영업 · 프리랜서','기타 · 현재 쉬는 중'])}<div class="consent-panel"><label class="consent-all"><input type="checkbox" id="consent-all">전체 동의</label>${consent('consent','[필수] 상담을 위한 개인정보 동의','수집·이용 주체: 썬파트너스. 목적: 파트너 상담 및 신청 의사 확인. 필수 항목: 이름, 연락처, 지역. 선택 항목: 상담가능시간, 연령대, 현재 역할. 보유기간: 수집일로부터 6개월 후 파기. 필수 동의를 거부하면 상담 신청이 어렵습니다.')}${consent('personalizationConsent','[선택] 맞춤 상담 정보 활용 동의','입력한 연령대와 현재 역할을 활용해 관심과 상황에 맞는 상담 정보를 안내합니다. 수집일로부터 6개월 또는 동의 철회 시까지 이용합니다. 거부해도 상담 신청이 가능합니다.')}${consent('marketingConsent','[선택] 제휴상품 마케팅 활용 동의','썬파트너스가 입력한 연락처와 상담 정보를 제휴상품 안내 목적으로 활용합니다. 제휴사에 개인정보를 제공하는 동의는 아닙니다. 수집일로부터 6개월 또는 동의 철회 시까지 이용하며, 거부해도 상담 신청이 가능합니다.')}${consent('advertisingConsent','[선택] 광고성 정보 수신 동의','선택한 채널로 썬파트너스의 상품·서비스 광고성 정보를 받습니다. 수집일로부터 6개월 또는 수신 동의 철회 시까지 적용됩니다. 거부해도 상담 신청이 가능합니다.')}<div class="consent-channels">${['전화','문자','카카오톡','이메일'].map(v=>`<label><input type="checkbox" name="channels" value="${v}">${v}</label>`).join('')}</div><label class="consult-field email-field" hidden>이메일<input type="email" name="email" autocomplete="email" placeholder="name@example.com"></label><details class="privacy-details"><summary>전체 개인정보처리방침 보기</summary><p>썬파트너스는 위 상담 및 동의한 안내 목적으로만 개인정보를 이용합니다. 필수·선택 항목과 이용기간은 각 동의 상세보기에서 확인할 수 있습니다. 보유기간이 끝나거나 삭제 요청이 접수되면 관련 법령상 보존 의무가 있는 경우를 제외하고 파기합니다. 별도 동의 없이 제휴사에 제공하지 않습니다. 개인정보 열람·정정·삭제 및 동의 철회는 상담 담당자에게 요청할 수 있습니다.</p></details></div><p class="consult-hint">선택 항목에 동의하지 않아도 상담을 신청할 수 있습니다.</p><div id="error" class="error" role="alert"></div><button class="consult-submit" id="submit" type="submit" disabled>상담 신청하기</button></form>`;
 document.body.append(dialog);const form=dialog.querySelector('form');
 const close=()=>{if(!submitting)dialog.close()};dialog.querySelector('.modal-close').onclick=close;dialog.oncancel=e=>{if(submitting)e.preventDefault()};dialog.onclose=()=>document.body.classList.remove('modal-open');
 const all=form.querySelector('#consent-all');const checks=[...form.querySelectorAll('.consent-panel input[type="checkbox"]')].filter(c=>c!==all);
 function update(){const ads=form.elements.advertisingConsent;const channels=[...form.querySelectorAll('[name="channels"]')];const email=channels.find(c=>c.value==='이메일').checked;form.querySelector('.email-field').hidden=!email;form.elements.email.required=email;all.checked=checks.every(c=>c.checked);all.indeterminate=!all.checked&&checks.some(c=>c.checked);form.querySelector('#submit').disabled=submitting||!form.checkValidity()||(ads.checked&&!channels.some(c=>c.checked));}
 all.onchange=()=>{checks.forEach(c=>c.checked=all.checked);update()};form.addEventListener('input',update);form.addEventListener('change',e=>{if(e.target.name==='channels'&&e.target.checked)form.elements.advertisingConsent.checked=true;if(e.target.name==='advertisingConsent'&&!e.target.checked)form.querySelectorAll('[name="channels"]').forEach(c=>c.checked=false);update()});
 form.elements.phone.oninput=e=>{const n=e.target.value.replace(/\D/g,'').slice(0,11);e.target.value=n.length>7?n.slice(0,3)+'-'+n.slice(3,7)+'-'+n.slice(7):n.length>3?n.slice(0,3)+'-'+n.slice(3):n;update()};
 form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity()||form.querySelector('#submit').disabled)return;const data=new FormData(form);answers=Object.fromEntries(data);delete answers.channels;answers.channels=data.getAll('channels');for(const k of ['consent','personalizationConsent','marketingConsent','advertisingConsent'])answers[k]=form.elements[k].checked;if(!answers.channels.includes('이메일'))delete answers.email;submitApplication()};
 dialog.showModal();document.body.classList.add('modal-open');}
document.querySelector('.brand').onclick=e=>{e.preventDefault();home()};home();

const ENDPOINT='https://script.google.com/macros/s/AKfycbyNaoYYZfa7uF4vv7Yub1Wc0UVXwpDI2ZX9fsRqp72sF7lvfmx-R70dXaTQ1z0WOEIn/exec';
let pendingRequest=null;
function submitApplication(){
 const button=document.getElementById('submit');if(!button||button.disabled)return;
 const fingerprint=JSON.stringify(answers);
 if(!pendingRequest||pendingRequest.fingerprint!==fingerprint)pendingRequest={fingerprint,id:crypto.randomUUID()};
 const requestId=pendingRequest.id;
 submitting=true;document.querySelectorAll('#partner-form input,#partner-form select').forEach(el=>el.disabled=true);button.disabled=true;button.textContent='신청 내용을 저장하고 있습니다…';
 document.getElementById('error').textContent='';
 document.querySelectorAll('.flow-nav button').forEach(b=>b.disabled=true);
 const iframe=document.createElement('iframe');iframe.name='receipt_'+requestId.replaceAll('-','');iframe.hidden=true;iframe.title='신청 접수 처리';
 const form=document.createElement('form');form.method='POST';form.action=ENDPOINT;form.target=iframe.name;form.hidden=true;
 const input=document.createElement('input');input.name='payload';input.value=JSON.stringify({...answers,requestId,consentVersion:'sunpartners-2026-09-21-v2',campaign:new URLSearchParams(location.search).get('utm_campaign')||'',website:''});form.append(input);
 let timer;
 function finish(ok,message){submitting=false;document.querySelectorAll('#partner-form input,#partner-form select').forEach(el=>el.disabled=false);clearTimeout(timer);window.removeEventListener('message',receive);form.remove();iframe.remove();
 if(ok){answers={};pendingRequest=null;document.getElementById('partner-form').innerHTML=`<section class="flow"><h2 tabindex="-1">상담 신청이<br>접수되었습니다.</h2><p>썬파트너스 담당자가 선택하신 시간대를 참고해 연락드리겠습니다.</p><p>접수번호: ${esc(requestId.slice(0,8))}</p><button class="cta" id="done">처음으로</button></section>`;document.getElementById('done').onclick=()=>{const d=document.getElementById('consult-dialog');d.close();d.remove()};document.querySelector('#partner-form h2').focus();}
 else{button.disabled=false;button.textContent='다시 신청하기';document.querySelectorAll('.flow-nav button').forEach(b=>b.disabled=false);document.getElementById('error').textContent=message;}}
 function receive(event){let origin;try{origin=new URL(event.origin)}catch{return}if(origin.protocol!=='https:'||!(origin.hostname==='script.googleusercontent.com'||origin.hostname.endsWith('.script.googleusercontent.com')||origin.hostname.endsWith('-script.googleusercontent.com')))return;
 const data=event.data;if(data?.kind!=='sunpartners-receipt'||data.requestId!==requestId)return;finish(data.ok===true,data.message||'저장하지 못했습니다. 다시 시도해주세요.');}
 window.addEventListener('message',receive);document.body.append(iframe,form);
 timer=setTimeout(()=>finish(false,'접수 확인이 지연되고 있습니다. 다시 신청해 주세요. 같은 신청은 중복 저장하지 않습니다.'),45000);form.submit();
}
